//@deno-types="npm:@types/express@4"

import express, { Request, Response } from "npm:express";

const app = express();

const wisdomArray: string[] = [
  "1. Don’t count your chickens before they hatch.",
  "2. Beer before liquor, never sicker.",
  "3. Ass, grass, or gas. Nobody rides for free.",
  "4. The best way to cope with stress is to confront it. Only then can you truly be happy or at least satisfied a little bit.",
  "5. Sometimes emotional stories don't fit into the rigid structure and you just have to embrace the chaos and not worry about it... as a family!",
  "6. A penny saved is a penny earned.",
  "7. Never press the big red button.",
  "8. Always bet on red.",
  "9. A little food, a little exercise, a lot of water.",
  "10. Check the estimated travel time the night before.",
  "11. If I can change, and you can change, we all can change.",
  "12. Nobody beats the wiz.",
  "13. No matter where you go, there you are.",
  "14. Homeownership is a scam.",
  "15. It's touCAN, not touCAN't.",
  "16. A moment on the lips, a lifetime on the hips.",
  "17. The greatest thing you'll ever learn is just to love and be loved in return.",
  "18. Whoever smelt it inhaled aerosolized fecal matter.",
  "19. Microwave ovens aren't all micro. Some are actually quite large.",
  "20. When your dentist says they're doing a full cavity search, ask them exactly what they mean by that.",
  "21. Find a job you enjoy doing with dogs and you'll never work a day in your life.",
  "22. People who think they have good voices always do. Keep singing!",
  "23. You can't have everything unless you're a bagel.",
  "24. The number of people older than you will never increase unless you're reverse aging.",
  "25. When time is running out and you don't know which wire to cut, go with yellow.",
  "26. When time is running out and you don't know which wire to cut, go with red.",
  "27. When time is running out and you don't know which wire to cut, go with blue.",
  "28. When time is running out and you don't know which wire to cut, go with green.",
  "29. If you lose your remote control, look behind the couch.",
  "30. Don't swim for thirty minutes after eating.",
  "31. Do eat for thirty minutes after swimming.",
  "32. Always salt your pasta water generously before it comes to a boil.",
  "33. No phones at the dinner table.",
  "34. Always bring milk with you to a protest in case you get pepper sprayed.",
  "35. Shop local!",
  "36. Food expiration dates are just a suggestion.",
  "37. You must take your place in the circle of life.",
  "38. Wash your face twice a day.",
  "39. Use a tinted moisturizer instead of foundation to improve your skin.",
  "40. You need to learn who you are outside of relationships or you will keep running away at your wedding.",
  "41. An eye for an eye makes the whole world blind.",
  "42. Remember to engage your core.",
  "43. Try to store a two-week supply of water in your home for emergencies.",
  "44. I before e except after c, sometimes.",
  "45. If you're line to vote before the polls close, stay in line!",
  "46. If you're ever on fire, stop, drop, and roll! Then stop again when it's out.",
  "47. If you're ever in a duel, aim up at the sky unless you're dueling Aaron Burr.",
  "48. Call your mother!",
  "49. Vanity will always lead to sadness.",
  "50. Enjoy what you already have.",
  "51. You can never go backwards.",
  "52. Baking soda is NOT the same as baking powder.",
  "53. Invest in that salad spinner!",
  "54. Read the whole recipe first.",
  "55. The hardest part of any new adventure is the first step.",
  "56. Believe in yourself and the world will follow.",
  "57. Loves arrives when you aren't looking for it.",
  "58. Always set your clock five minutes early.",
  "59. Always put it in writing!",
  "60. Some questions ARE dumb.",
  "61. Quality, not quantity.",
  "62. Everything worthwhile takes time.",
  "63. For the best curls, dry your hair with a t-shirt, not a towel.",
  "64. Always cut your steak against the grain.",
  "65. Don't take advice from cartoon aliens.",
  "66. If it's yellow let it mellow, if it's brown flush it down. If it's crying: oh no.",
  "67. Every meeting can be a phone call and every phone call can be an email.",
  "68. A watched pot never boils.",
  "69. Don't judge a book by it's cover.",
  "70. If you love something, let it go. If it come backs to you, it's yours forever. If it doesn't, then it was never meant to be.",
  "71. A bird in the hand is worth two in the bush.",
  "72. Buy bitcoin 10 years ago.",
  "73. Thaw the turkey before you put it in the deep fryer.",
  "74. Two people can keep a secret if one of them is dead.",
  "75. Don't write anything in an email you wouldn’t want read in family court.",
  "76. Better to just shave it all off. Nobody's buying that comb over.",
  "77. Sometimes it's best to just sit down and shut your mouth.",
  "78. TRUST NO ONE.",
  "79. It's okay to fart if no one will hear you and it won't smell too badly.",
  "80. Quit smoking now for bonus days on your life.",
  "81. The only thing worse than accidentally letting all the hogs out of the barn is lying to grandma about it.",
  "82. Money isn't everything but it is still very important.",
  "83. Don't expect to go to prom if you smell like a sewer.",
  "84. Nobody likes a ball hog (in sports but also in the bedroom and the ballroom).",
  "85. Everyone is expendable.",
  "86. Don't ruin the family's vacation over a petty argument. The petty argument can wait until everyone's home and you're not paying a fortune every night for a hotel room.",
  "87. Never call your sister that word!",
  "88. Don't lie about being sick because you wanted to go to the battle of the bands instead of having dinner with your sister's old roommate.",
  "89. Snitches get stitches.",
  "90. Don't sell your soul for $5.",
  "91. A man should treat his wife as well as he treats the hotrod he's rebuilding in the garage.",
  "92. You must know when to hold 'em, but also you must know when to fold 'em (talking about blankets).",
  "93. Never drink from a public water fountain without checking all your angles.",
  "94. If someone has you in a rear naked choke, fight their hands and get your back to the ground.",
  "95. A man who has friends is a rich man indeed. Just not with money.",
  "96. Pain is just weakness leaving the body.",
  "97. Follow your fear. Scare your fear in a garage at night. Send your fear anonymously threatening notes.",
  "98. Drink water upside down to get rid of hiccups. BOO!",
  "99. When you get a chance to sit it out or dance ---- dance.",
  "100. Yesterday is history, tomorrow is a mystery, but today is a gift, that's why they call it the present.",
  "101. Don't cry over spilled milk, you baby.",
  "102. Clear eyes, full hearts, can't lose.",
  "103. Teamwork makes the dream work.",
  '104. There\'s no "I" in team, but there is a me, meat, tame, mate, eat, ate, mat...',
  "105. Hang in there.",
  "106. Don't give up, you've got a reason to live. You can't forget, you only get what you give.",
  "107. Make pay while the sun shines.",
  "108. High Yield Savings accounts are a joke.",
  "109. Pay into your 401k early and often, especially if your company will match it.",
  "110. A hotdog may be a sandwich but a hoagie isn't.",
  "111. It's a real shame they're called tote bags and not totes bags.",
  "112. Just because you can doesn't mean you should make your bed everyday.",
  "113. Never leave the house without an amulet that's been blessed by a witch.",
  "114. TV writing is not for the faint of arms, neither is regular writing.",
  "115. Dance like everyone's watching.",
  "116. Never put table salt on your nightstand.",
  "117. Talking is for closers.",
  "118. Make love not onion rings.",
  "119. Water signs are b*tches, Earth signs get stitches.",
  "120. They tried to bury us, they didn't know we were gophers.",
  "121. To beet or not to beet, that is the question.",
  "122. Ceramics is a really competitive industry, but breaking in isn't as hard as you think.",
  "123. Affirmations are for the birds.",
  "124. The number of people older than you will never increase unless you're reverse aging.",
  "125. All play and no work makes you the life of the partay!",
  "126. A leopard cannot change its spots without a sci-fi ray or at least some markers.",
  "127. Wash your hands for at least a hundred seconds.",
  "128. Don't cheat on your wife, you're better than that.",
  "129. Cats get to choose who holds them.",
  "130. Moderation, all the time.",
  '131. Make sure someone is looking at your before you throw something to them. Yelling "heads up" just isn\'t enough.',
  "132. Condoms expire.",
  "133. Just make two trips carrying the groceries.",
  "134. If you're making a noise while trying to push out a dump, then calm down and lean back.",
  "135. Don't make one genre of music your whole thing.",
  "137. Soft bristles, gentle brushing. The firm bristles are going to mess up your enamel.",
  "138. Write a little every day.",
  "139. Assume that bad drivers are only acting like that because they're holding a fish bowl while trying to get home from the pet store.",
  "140. Cut your family some slack.",
  "141. Restart your computer every once in a while.",
  "142. You can check your subscriptions by going to your account in settings.",
  "143. Be kind.",
  "144. Life is just over after you die, so make the best of it and help other people while you're around.",
  "145. Don't take investing advice from social media.",
  "146. Don't look right at the laser pointer.",
  "147. If you can't say something nice, don't say anything at all.",
  '149. When "god" closes a door, he opens a window.',
  "150. Don't bite off more than you can chew, you little scamp.",
  "151. Shrimp for breakfast is diarrhea city.",
  "152. If you masturbate too much you actually will go blind. Trust me.",
  "153. It's not the size of the ship, it's about the motion of the ocean (unless you have a really small embarassing ship).",
  "154. Call your grandma. BUT NOT GRANDPA.",
  "155. Don't text your ex. Write them a long, devastating letter on expensive paper and have a bird deliver it.",
  "156. If someone tells you they love you just as you are, they are your soulmate. They're also your soulmate if they're a hot British lawyer.",
  "157. Just because you are the loudest, doesn't make you wrong.",
  "158. If you're on a school trip in Rome and everyone treats you like a celebrity, you probably have an Italian pop star doppleganger.",
  "159. Buy a sink strainer.",
  "160. An apple a day keeps the doctor away. A doctor a day makes the you the mysterious doctor kidnapper.",
  "161. If it looks like a shlorduck, swims like a shlorduck, and quacks like a shlorduck, then it probably is a shlorduck.",
  "162. Don't get mad, get even.",
  "163. Always double cleanse.",
  "164. Never over exfoliate.",
  "165. Listen you your heart. If it's really loud you might be dehydrated.",
  "166. Don't bite the hand that feeds you.",
  "167. Don't put all your eggs in one basket.",
  "168. Look both ways before crossing the street.",
  "169. Your parents were once hot. Food for thought.",
  "170. The answer is blowing in the wind.",
  "171. Floss, then brush.",
  "172. Brush, then floss.",
  "173. Don't mess with Texas.",
  "174. He who cannot be a good follower, cannot be a good leader.",
  "175. Those who knows, do. Those that understand, teach.",
  "176. Educating the mind without educating the heart is no education at all.",
  "177. Don't count your chickens before they hatch.",
  "178. If it's spicy going in, it's spicy going out (the butthole.)",
  "179. If it ain't broke, dain't fix it.",
  "180. The customer is always right.",
  "181. Reduce, reuse, recycle, repent.",
  "182. When giving a high five, look at the other person's elbow. Some thing works for kissing.",
  "183. Always have a song ready just in case you get passed the AUX.",
  "184. Clout is king.",
  "185. Your parents got a house for two acorns and a handshake. It's okay that you're still renting.",
  "186. Tragedy plus time equals comedy.",
  "187. Crack is in fact wack. Sorry",
  '188. Keep texting even though they angrily said "bye".',
  '189. Yelling "on me" doesn\'t help your squad.',
  "190. Don't ever let anyone convince you that you don't like what you like.",
  "191. If it’s your turn to freestyle, don’t steal a verse you heard on the radio. Rap from the heart, yo.",
];

app.get("/", (req: Request, res: Response): void => {
  res.send(wisdomArray[Math.floor(Math.random() * wisdomArray.length)]);
});

app.get("/:number", (req: Request, res: Response): void => {
  const number = req.params.number;
  res.send(
    number > wisdomArray.length || number <= 0
      ? wisdomArray[0]
      : wisdomArray[number - 1]
  );
});

app.listen(3000, () => {
  console.log("Server is running on port 3000");
});
