//@deno-types="npm:@types/express@4"

import express, { Request, Response } from "npm:express";

const app = express();

const wisdomArray: string[] = [
  "Don’t count your chickens before they hatch.",
  "Beer before liquor, never sicker.",
  "Ass, grass, or gas. Nobody rides for free.",
  "The best way to cope with stress is to confront it. Only then can you truly be happy or at least satisfied a little bit.",
  "Sometimes emotional stories don't fit into the rigid structure and you just have to embrace the chaos and not worry about it... as a family!",
  "A penny saved is a penny earned.",
  "Never press the big red button.",
  "Always bet on red.",
  "A little food, a little exercise, a lot of water.",
  "Check the estimated travel time the night before.",
  "If I can change, and you can change, we all can change.",
  "Nobody beats the wiz.",
  "No matter where you go, there you are.",
  "Homeownership is a scam.",
  "It's touCAN, not touCAN't.",
  "A moment on the lips, a lifetime on the hips.",
  "The greatest thing you'll ever learn is just to love and be loved in return.",
  "Whoever smelt it inhaled aerosolized fecal matter.",
  "Microwave ovens aren't all micro. Some are actually quite large.",
  "When your dentist says they're doing a full cavity search, ask them exactly what they mean by that.",
  "Find a job you enjoy doing with dogs and you'll never work a day in your life.",
  "People who think they have good voices always do. Keep singing!",
  "You can't have everything unless you're a bagel.",
  "The number of people older than you will never increase unless you're reverse aging.",
  "When time is running out and you don't know which wire to cut, go with yellow.",
  "When time is running out and you don't know which wire to cut, go with red.",
  "When time is running out and you don't know which wire to cut, go with blue.",
  "When time is running out and you don't know which wire to cut, go with green.",
  "If you lose your remote control, look behind the couch.",
  "Don't swim for thirty minutes after eating.",
  "Do eat for thirty minutes after swimming.",
  "Always salt your pasta water generously before it comes to a boil.",
  "No phones at the dinner table.",
  "Always bring milk with you to a protest in case you get pepper sprayed.",
  "Shop local!",
  "Food expiration dates are just a suggestion.",
  "You must take your place in the circle of life.",
  "Wash your face twice a day.",
  "Use a tinted moisturizer instead of foundation to improve your skin.",
  "You need to learn who you are outside of relationships or you will keep running away at your wedding.",
  "An eye for an eye makes the whole world blind.",
  "Remember to engage your core.",
  "Try to store a two-week supply of water in your home for emergencies.",
  "I before e except after c, sometimes.",
  "If you're line to vote before the polls close, stay in line!",
  "If you're ever on fire, stop, drop, and roll! Then stop again when it's out.",
  "If you're ever in a duel, aim up at the sky unless you're dueling Aaron Burr.",
  "Call your mother!",
  "Vanity will always lead to sadness.",
  "Enjoy what you already have.",
  "You can never go backwards.",
  "Baking soda is NOT the same as baking powder.",
  "Invest in that salad spinner!",
  "Read the whole recipe first.",
  "The hardest part of any new adventure is the first step.",
  "Believe in yourself and the world will follow.",
  "Loves arrives when you aren't looking for it.",
  "Always set your clock five minutes early.",
  "Always put it in writing!",
  "Some questions ARE dumb.",
  "Quality, not quantity.",
  "Everything worthwhile takes time.",
  "For the best curls, dry your hair with a t-shirt, not a towel.",
  "Always cut your steak against the grain.",
  "Don't take advice from cartoon aliens.",
  "If it's yellow let it mellow, if it's brown flush it down. If it's crying: oh no.",
  "Every meeting can be a phone call and every phone call can be an email.",
  "A watched pot never boils.",
  "Don't judge a book by its cover.",
  "If you love something, let it go. If it come backs to you, it's yours forever. If it doesn't, then it was never meant to be.",
  "A bird in the hand is worth two in the bush.",
  "Buy bitcoin 10 years ago.",
  "Thaw the turkey before you put it in the deep fryer.",
  "Two people can keep a secret if one of them is dead.",
  "Don't write anything in an email you wouldn’t want read in family court.",
  "Better to just shave it all off. Nobody's buying that comb over.",
  "Sometimes it's best to just sit down and shut your mouth.",
  "TRUST NO ONE.",
  "It's okay to fart if no one will hear you and it won't smell too badly.",
  "Quit smoking now for bonus days on your life.",
  "The only thing worse than accidentally letting all the hogs out of the barn is lying to grandma about it.",
  "Money isn't everything but it is still very important.",
  "Don't expect to go to prom if you smell like a sewer.",
  "Nobody likes a ball hog (in sports but also in the bedroom and the ballroom).",
  "Everyone is expendable.",
  "Don't ruin the family's vacation over a petty argument. The petty argument can wait until everyone's home and you're not paying a fortune every night for a hotel room.",
  "Never call your sister that word!",
  "Don't lie about being sick because you wanted to go to the battle of the bands instead of having dinner with your sister's old roommate.",
  "Snitches get stitches.",
  "Don't sell your soul for $5.",
  "A man should treat his wife as well as he treats the hotrod he's rebuilding in the garage.",
  "You must know when to hold 'em, but also you must know when to fold 'em (talking about blankets).",
  "Never drink from a public water fountain without checking all your angles.",
  "If someone has you in a rear naked choke, fight their hands and get your back to the ground.",
  "A man who has friends is a rich man indeed. Just not with money.",
  "Pain is just weakness leaving the body.",
  "Follow your fear. Scare your fear in a garage at night. Send your fear anonymously threatening notes.",
  "Drink water upside down to get rid of hiccups. BOO!",
  "When you get a chance to sit it out or dance ---- dance.",
  "Yesterday is history, tomorrow is a mystery, but today is a gift, that's why they call it the present.",
];

app.get("/", (req: Request, res: Response): void => {
  res.send(wisdomArray[Math.floor(Math.random() * wisdomArray.length)]);
});

app.listen(3000, () => {
  console.log("Server is running on port 3000");
});
